= Erste Schritte eines IPv6 Stacks

[.lead]
Ein kleiner, experimenteller IPv6-Stack zum Lernen und Ausprobieren.
Fürs Erste wird nur macOS arm64 unterstützt.

== Aktueller Stand

Der Stack kann aktuell unter anderem:

* IPv6-Pakete empfangen und senden
* ICMPv6 Echo Requests beantworten (Ping)
* ICMPv6 Destination Unreachable erzeugen
* ICMPv6 Time Exceeded erzeugen
* ICMPv6 Packet Too Big erzeugen
* ICMPv6 No Route to Host erzeugen
* UDP-Pakete empfangen und beantworten
* UDP-Echo als einfachen Test verwenden (Alle Ports außer Port 13)
* UDP-Daytime auf Port 13 verwenden

Einige der ICMPv6-Fehlerfälle sind aktuell noch bewusst vereinfacht
implementiert und dienen hauptsächlich zum Testen des Stacks.

== Bauen und ausführen

[source,sh]
----
dotnet publish -c Release -r osx-arm64 --self-contained
sudo ./bin/Release/net9.0/osx-arm64/publish/TunTest
----

== IP-Adresse zuweisen

Aktuell bekommt die Schnittstelle im Stack die `fd00::2/64`.
Der Client kann daher die `fd00::1/64` haben.
Das ist fürs Erste fest vorgegeben.

[source,sh]
----
sudo ifconfig utun10 inet6 fd00::1/64 up
----

== Ping testen

Die Schnittstelle kann mittels `ping6` angepingt werden:

[source,sh]
----
ping6 -c 3 fd00::2
----

Beispiel:

----
PING6(56=40+8+8 bytes) fd00::1 --> fd00::2
16 bytes from fd00::2, icmp_seq=0 hlim=64 time=0.202 ms
16 bytes from fd00::2, icmp_seq=1 hlim=64 time=0.265 ms
16 bytes from fd00::2, icmp_seq=2 hlim=64 time=0.294 ms

--- fd00::2 ping6 statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/std-dev = 0.202/0.254/0.294/0.038 ms
----

== UDP testen

Der Stack unterstützt aktuell einen einfachen UDP-Echo-Modus.
Dabei wird jedes empfangene UDP-Paket unabhängig vom Zielport mit
dem gleichen Payload zurückgesendet.

[source,sh]
----
nc -u -6 fd00::2 9999
----

Anschließend kann beispielsweise Text eingegeben werden:

----
Papagei
Papagei
----

Die zweite Zeile stammt dabei vom UDP-Echo des eigenen Stacks.

== Traceroute testen

Da der Stack ICMPv6 Time Exceeded unterstützt, kann auch `traceroute6`
zum Testen verwendet werden:

[source,sh]
----
traceroute6 fd00::2
----

== Hinweise

Der Stack befindet sich noch in einer frühen Entwicklungsphase.
Viele Funktionen sind zunächst bewusst minimal implementiert.

Aktuell wird ausschließlich IPv6 über ein TUN-Interface verwendet.
Layer-2-Funktionen wie Ethernet, NDP und Router Discovery sind noch
nicht Bestandteil der Implementierung.