<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        
        <!-- Native AOT aktivieren -->
        <PublishAot>true</PublishAot>

        <!-- Optionale Optimierungen für maximale Performance -->
        <OptimizationPreference>Speed</OptimizationPreference>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Tests\" />
    </ItemGroup>

</Project>
